/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "s21_3dv.h"

START_TEST(s21_3dv1) {
  char *file = "cube-2.obj";
  struct data *obj;
  obj = (struct data *)malloc(sizeof(struct data));
  read_obj_file(file, obj);
  int facets_count_check = 60;
  int vertex_count_check = 27;
  int arr_of_facets_check[60] = {1, 7, 7, 5, 5, 1, 1, 3, 3, 7, 7, 1, 1, 4, 4,
                                 3, 3, 1, 1, 2, 2, 4, 4, 1, 3, 8, 8, 7, 7, 3,
                                 3, 4, 4, 8, 8, 3, 5, 7, 7, 8, 8, 5, 5, 8, 8,
                                 6, 6, 5, 1, 5, 5, 6, 6, 1, 1, 6, 6, 2, 2, 1};
  double arr_of_vertexes_check[27] = {
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 2.0, 0.0, 0.0, 2.0,
      2.0, 2.0, 0.0, 0.0, 2.0, 0.0, 2.0, 2.0, 2.0, 0.0, 2.0, 2.0, 2.0};
  ck_assert_int_eq(facets_count_check, obj->count_of_facets);
  ck_assert_int_eq(vertex_count_check, obj->count_of_vertexes);
  for (int i = 0; i < facets_count_check; i++) {
    ck_assert_int_eq(arr_of_facets_check[i], obj->facets_arr[i]);
  }
  for (int i = 0; i < vertex_count_check; i++) {
    ck_assert_int_eq(arr_of_vertexes_check[i], obj->vertex_arr[i]);
  }

  move_obj(obj, 1.0, 1);
  move_obj(obj, 1.0, 2);
  move_obj(obj, 1.0, 3);
  double move_of_vertexes_check[27] = {
      0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 3.0, 1.0, 1.0, 3.0,
      3.0, 3.0, 1.0, 1.0, 3.0, 1.0, 3.0, 3.0, 3.0, 1.0, 3.0, 3.0, 3.0};
  for (int i = 0; i < vertex_count_check; i++) {
    ck_assert_int_eq(move_of_vertexes_check[i], obj->vertex_arr[i]);
  }

  scale_obj(obj, 2);
  double scale_of_vertexes_check[27] = {
      0.0, 0.0, 0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 6.0, 2.0, 6.0, 2.0, 2.0, 6.0,
      6.0, 6.0, 2.0, 2.0, 6.0, 2.0, 6.0, 6.0, 6.0, 2.0, 6.0, 6.0, 6.0};
  for (int i = 0; i < vertex_count_check; i++) {
    ck_assert_int_eq(scale_of_vertexes_check[i], obj->vertex_arr[i]);
  }

  rotate_x(obj, 360, 1);
  rotate_x(obj, 360, 2);
  rotate_x(obj, 360, 0);
  double rotate_of_vertexes_check[27] = {
      0.0, 0.0, 0.0, 2.0, 2.0, 2.0, 1.0, 2.0, 6.0, 2.0, 6.0, 1.0, 1.0, 6.0,
      5.0, 6.0, 1.0, 2.0, 5.0, 2.0, 6.0, 6.0, 5.0, 1.0, 6.0, 6.0, 6.0};
  for (int i = 0; i < vertex_count_check; i++) {
    ck_assert_int_eq(rotate_of_vertexes_check[i], obj->vertex_arr[i]);
  }
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_3dv1);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
